{
    'name': 'Hospital Management System',
    'version': '10.0.1.0.0',
    'summary': 'Manages Hospital Records',
    'sequence': '1',
    'category': 'Extra Tools',
    'license': 'AGPL-3',
    'author': 'Dishon Kadoh',
    'maintainer': 'Dishon Kadoh',
    'website': 'dkadoh92@gmail.com',
    'depends': ['base', 'mail', 'sale'],
    'data': ['security/ir.model.access.csv',
             'security/security.xml',
             'wizards/create_appointment.xml',
             'data/sequence.xml',
             'views/appointment.xml',
             'views/doctor.xml',
             'views/patient.xml',
             'report/report.xml'],
    'demo': ['demo/demo.xml'],
    'application': True,
    'installable': True,
    'auto_install': False,

}
